defaults:
  vectordb: chroma
  embeddings: fastembed


routes:
  - name: chitchat
    utterances:
      - "what's up"
      - "how's the weather today?"
      - "how are things going?"
      - "let's go to the chippy"
      - "what's going on?"
    model_id: llm:meta-llama/Llama-3.1-8B-Instruct
    inference_provider: cerebras
    api_url: https://router.huggingface.co/v1/chat/completions

  - name: politics
    utterances:
      - "tell me about the president"
      - "isn't politics the best thing ever"
      - "why don't you tell me about your political opinions"
      - "don't you just love the president"
      - "they're going to destroy this country!"
    model_id: llm:Qwen/Qwen3-Next-80B-A3B-Instruct
    inference_provider: novita
    api_url: https://router.huggingface.co/v1/chat/completions
