routes:
  - name: chitchat
    utterances:
      - "what's up"
      - "how's the weather today?"
      - "how are things going?"
      - "lovely weather today"
      - "the weather is horrendous"
      - "let's go to the chippy"
    action: llm:llama-3.3-70b-versatile


  - name: politics
    utterances:
      - "tell me about the president"
      - "isn't politics the best thing ever"
      - "why don't you tell me about your political opinions"
      - "don't you just love the president"
      - "they're going to destroy this country!"
      - "they will save the country!"
    action: llm:Qwen3-Next-80B-A3B-Instruct

