routes:
  - name: chitchat
    utterances:
      - "what's up"
      - "how's the weather today?"
      - "how are things going?"
      - "lovely weather today"
      - "the weather is horrendous"
      - "let's go to the chippy"
      - "what's going on?"
      - "how are you doing?"
      - "how's your day?"
      - "what's new with you?"
      - "is it sunny outside?"
      - "is it raining today?"
      - "such a beautiful morning"
      - "terrible weather today"
      - "let's grab some coffee"
      - "want to go out tonight?"
      - "do you like pizza?"
      - "I'm feeling great today"
      - "not in the mood today"
      - "let's hang out later"
      - "what are your weekend plans?"
      - "how's life treating you?"
      - "did you sleep well?"
      - "good morning"
      - "good night"
      - "see you later"
      - "catch you soon"
      - "where are you headed?"
      - "let's go for a walk"
      - "want to play a game?"
      - "do you like movies?"
      - "seen any good shows?"
      - "how's your family?"
      - "how's work going?"
      - "what do you think about AI?"
      - "let’s talk about hobbies"
      - "do you play any sports?"
      - "do you like music?"
      - "what kind of food do you like?"
      - "let’s cook something nice"
      - "how was your day yesterday?"
      - "do you enjoy traveling?"
      - "where have you traveled?"
      - "ever been abroad?"
      - "do you like books?"
      - "what are you reading?"
      - "can you tell me a joke?"
      - "that was funny"
      - "tell me another one"
      - "you’re hilarious"
      - "what’s your favorite color?"
      - "what’s your favorite animal?"
      - "do you have pets?"
      - "what’s your favorite movie?"
      - "what’s your favorite song?"
      - "let’s dance"
      - "let’s sing"
      - "are you bored?"
      - "let’s do something fun"
      - "can you solve riddles?"
      - "tell me a riddle"
      - "do you like puzzles?"
      - "what’s your favorite place?"
      - "do you like the beach?"
      - "do you like the mountains?"
      - "let’s go hiking"
      - "let’s go swimming"
      - "let’s go running"
      - "let’s exercise together"
      - "do you like yoga?"
      - "do you like meditation?"
      - "how do you relax?"
      - "what do you do for fun?"
      - "let’s talk about friends"
      - "do you like comedy?"
      - "do you like action movies?"
      - "do you like horror?"
      - "what’s your favorite drink?"
      - "do you like tea?"
      - "do you like coffee?"
      - "let’s grab some snacks"
      - "are you hungry?"
      - "what’s for dinner?"
      - "do you cook often?"
      - "let’s order food"
      - "do you use delivery apps?"
      - "have you been shopping?"
      - "do you like fashion?"
      - "do you like technology?"
      - "what’s your phone model?"
      - "do you use social media?"
      - "which app do you use most?"
      - "let’s chat online"
      - "do you play video games?"
      - "what’s your favorite game?"
      - "do you like board games?"
      - "what’s trending right now?"
      - "let’s talk about memes"
      - "show me something funny"
    action: llm:llama-3.3-70b-versatile

  - name: politics
    utterances:
      - "tell me about the president"
      - "isn't politics the best thing ever"
      - "why don't you tell me about your political opinions"
      - "don't you just love the president"
      - "they're going to destroy this country!"
      - "they will save the country!"
      - "what do you think of democracy?"
      - "do you support freedom of speech?"
      - "what’s your opinion on elections?"
      - "who will win the next election?"
      - "what’s your stance on taxes?"
      - "do you like capitalism?"
      - "do you like socialism?"
      - "what do you think about communism?"
      - "tell me about dictatorships"
      - "is democracy the best system?"
      - "what do you think of monarchies?"
      - "how do parliaments work?"
      - "what’s a senate?"
      - "what’s a prime minister?"
      - "tell me about political parties"
      - "why do people protest?"
      - "is voting important?"
      - "who is running for office?"
      - "what’s a political rally?"
      - "tell me about campaigns"
      - "what’s your view on corruption?"
      - "what’s your view on transparency?"
      - "do you support government surveillance?"
      - "tell me about free press"
      - "what’s your stance on climate policy?"
      - "what do you think of foreign policy?"
      - "how do wars affect politics?"
      - "do you believe in peace talks?"
      - "what is diplomacy?"
      - "what’s NATO?"
      - "what’s the UN?"
      - "how do treaties work?"
      - "do you trust politicians?"
      - "why do politicians lie?"
      - "can politics be honest?"
      - "what’s the difference between left and right?"
      - "what’s conservative?"
      - "what’s liberal?"
      - "what’s progressive?"
      - "what’s nationalist?"
      - "what’s populist?"
      - "tell me about policies"
      - "what’s a manifesto?"
      - "why do governments fail?"
      - "how do revolutions happen?"
      - "tell me about coups"
      - "what’s a dictatorship?"
      - "is freedom guaranteed?"
      - "who makes the laws?"
      - "what’s a constitution?"
      - "do you trust the judiciary?"
      - "tell me about checks and balances"
      - "how do elections work?"
      - "do you vote?"
      - "who counts the votes?"
      - "what’s gerrymandering?"
      - "tell me about lobbying"
      - "is corruption inevitable?"
      - "what’s the role of the media?"
      - "what’s propaganda?"
      - "how does censorship work?"
      - "what’s fake news?"
      - "tell me about political scandals"
      - "why do politicians debate?"
      - "what’s parliament?"
      - "how do laws pass?"
      - "what’s executive power?"
      - "tell me about the judiciary"
      - "how do constitutions change?"
      - "what’s martial law?"
      - "tell me about civil rights"
      - "tell me about human rights"
      - "what’s universal suffrage?"
      - "do you support equal rights?"
      - "what’s discrimination in politics?"
      - "tell me about minority rights"
      - "what’s women’s suffrage?"
      - "tell me about political ideologies"
      - "do ideologies change?"
      - "how does globalization affect politics?"
      - "tell me about international law"
      - "who are the world leaders?"
      - "how do leaders cooperate?"
      - "why do countries fight?"
      - "what’s economic policy?"
      - "what’s foreign investment?"
      - "what’s public policy?"
      - "tell me about healthcare policy"
      - "what’s education policy?"
      - "what’s welfare policy?"
      - "do you believe in free markets?"
      - "what’s regulation?"
      - "what’s deregulation?"
      - "what’s political reform?"
      - "why do governments reform?"
      - "what’s revolution?"
    action: llm:Qwen3-Next-80B-A3B-Instruct
